---
title: "Rapport SBR V1"
author: "ETTADLAOUI Othmane ; DIAKITE Abdoul Oudouss"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    number_sections: yes
  word_document: 
    toc: yes
    toc_depth: 6
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Histoire de l'assurance au maroc:
Pendant longtemps, l'assurance au Maroc n'a pas été toujours une culture de nos ancêtres. Cette notion  a été considérée comme immorale car elle développait la négligence et l'idee de pari. L'assurance aussi a été inacceptable par le système juridique islamique,En excluant les besoins de la croissance économique.
Ainsi que, Le faible pouvoir d'achat de la plupart des couches de la population qui considèrent l'assurance comme un produit de luxe, réservé seulement aux marocains issus de la classe à revenu élevé, constituait en partie un véritable handicap au développement naturel de ce secteur. Pour toutes ces raisons, l'assurance, toutes branches confondues, totalement étrangère à la tradition juridique du pays, n'a pu voir le jour qu'après l'avènement du protectorat.

Au fil du temps, cette pratique a réussi à se tisser une place dans la société marocaine. Les premières compagnies d'assurances étaient des compagnies étrangères travaillant dans le domaine de l'assurance maritime, et ce n'est qu'après, que cette activité a pu se généraliser pour toucher d'autres secteurs avec notamment l’arrivée de nouveaux besoins (santé, automobile, biens divers…)

# La construction de la courbe des taux zéro-coupon :
Dans cette partie nous nous intéressons à la construction de la courbe des taux zéro-coupon dont nous avons besoin dans le reste de ce travaille afin d’actualiser les flux futurs entrant dans le calcul des différentes BEST ESTIMATE. Les taux Zéro Coupons sont extraite à partir des taux moyens pondérés des transactions des bons de trésor publiées par BANK AL MAGHRIB. Ces taux en fait, sont des taux monétaires pour les maturités inférieures ou égales à un an, alors qu’il représente un taux actuariel pour les maturités supérieures à un an, de plus ils ne sont disponibles que pour certaines maturités (Remarque : Insérant une figure).

Pour cette raison on va suivre les étapes suivantes pour la construction de la courbe des taux zéro-coupon :

- 1ere étape : Transformation des taux monétaires en taux actuariels.
- 2eme étape :  Interpolation linéaire afin d’obtenir des taux actuariels pour des maturités pleines.
-	3eme étape : Calcule des taux zéro coupons à partir des taux actuariels des maturités pleines par la Méthode du Bootstrap.
-	4eme étape : Extrapolation de la courbe des taux zéro-coupon pour des maturités non observées lointaines par la méthode de Smith-Wilson

## Transformation des taux monétaires en taux actuariels :
Cette étape consiste à transformer les taux monétaires à des taux actuariels en utilisant la relation suivante :
$$
T_a=(1+\frac{n}{360}*T_m )^{\frac{365}{n}}-1
$$
Avec :

$T_a$ : Le taux actuariel.

$T_m$  : Le taux monétaire.

$n$ :  Le nombre de jours entre la date de valeur et la date d’échéance.

$\frac{365}{n}$  : La maturité

Après l’application de cette formule sur Les données de marché marocain (publie par la BAM), nous avons obtenu les résultats situés dans le tableau suivant : (Remarque insertions des résultats obtenu par l’application)

## Interpolation linéaire de la courbe des taux actuariels :
En réalité nous disposons que des taux actuariels des maturités ayant des valeurs décimales, le but de cette étape est donc la détermination des taux actuariels avec des maturités pleines en utilisant une interpolation linéaire.

Cette opération consiste à déterminer Le DPL qui correspond au dernier point liquide. Il est déterminé de sorte que le volume cumulé des obligations dont les échéances sont supérieures au DPL est inférieur à 6% du volume total des transactions prises en compte pour la construction de la courbe des taux zéro-coupon. Il correspond aussi à dernière maturité observable.

La formule d’interpolation pour toute maturité j allant de 1, 2, . . ., DPL est la suivante : $$
t_j=t_i+\frac{t_{i+1 }-t_i}{n_{i+1 }-n_i} *(j-n_i )
$$

Avec :   

$t_j$ : Taux actuariels de maturité pleine j compris entre les maturités n_i et n_(i+1).
  
$t_i$ : Taux actuariels de maturités n_i.

## la méthode de Bootstrap:

Le Bootstrap est une technique de reconstitution de la courbe zéro-coupon pas à pas, en déterminant les taux zéro-coupon à partir des taux actuariels, en faisant l'hypothèse que le prix théorique d'une obligation correspond à la somme de ses flux futures actualisés aux taux zéro-coupon de l'échéance de chaque flux. Ainsi, on suppose que les prix des obligations des Bons du trésor sont au pair, c’est-à-dire que le prix d’émission des obligations des bons du trésor et leur valeur nominale sont égaux.

-	**Pour une maturité inferieure ou égale a un an** :

Le taux zéro-coupon est donc le taux actuariel de même maturité. Car aucun coupon n’est payé avant l’échéance.

-	**Pour une maturité supérieure à un an** :

Le taux zéro-coupon est calculé par la formule suivante : 
$$
R_n =  ^{n}\sqrt{\frac{1+t_n}{1-t_n + \sum_{i=1}^{n} \frac{1}{(1+R_i)^{i}}}} - 1
$$


(ajouter le graphique et le tableau après calcule de ZC).

## Extrapolation de la courbe des taux zéro-coupon : méthode de Smith-Wilson
La méthode Smith-Wilson est une méthode d'extrapolation de la courbe des taux d'intérêt développée par les chercheurs Smith et Wilson en 1995, et est utilisée pour extrapoler les taux à long terme. Son principe est d'ajuster une courbe mathématique à la courbe des taux observée sur le marché, en utilisant une fonction spécifique appelée "fonction de Smith-Wilson". Cette fonction est une combinaison de deux termes : le premier terme représente une fonction de décroissance exponentielle, qui est utilisée pour modéliser la partie courte de la courbe des taux ; le second terme est une fonction polynomiale qui est utilisée pour modéliser la partie longue de la courbe des taux.  

Une fois que la fonction de Smith-Wilson a été ajustée à la courbe des taux, elle peut être utilisée pour extrapoler les taux pour des maturités plus longues que celles disponibles sur le marché. Cette extrapolation est possible car la fonction de Smith-Wilson est conçue pour s'adapter de manière continue à la fois à la partie courte et à la partie longue de la courbe des taux.

dans ce modèle le taux à terme à long terme est un paramètre d’entrée fixe qui ne varie pas dans le temps à mesure qu’évoluent les prix des obligations. Elle permet aux taux à terme à long terme de converger vers le taux « infini »(Ultimate Forward Rate) choisi et elle offre une base solide pour couvrir le risque de taux d’intérêt à long terme.

Les paramètres d’entrée sont les suivants :

- le UFR (Ultimate Forward Rate)
- $\alpha$ la vitesse de convergence vers le UFR.

En fait, sur le marché on observe les prix zéro-coupons de différentes maturités
$u_1, u_2, . . . , u_N$ alors Smith-Wilson suppose que le facteur d’actualisation $P(\tau) $ est  déterminé par:
$$
P(\tau) = e^{-UFR * \tau} + \sum_{j=1}^N \gamma_j * W(\tau , \mu_j)
$$

Où: 
$$
W(\tau , \mu_j) =  e^{-UFR * (\tau + \mu_j )} * [ \alpha * min(\tau , \mu_j) - 0,5 *e^{-\alpha*max(\tau , \mu_j)}*(e^{\alpha*min(\tau , \mu_j)}- e^{-\alpha*max(\tau , \mu_j)} ) ] 
$$

Avec : 
- $W$ représente un ensemble de fonctions à noyau pour chaque prix d’obligation observable d’entrée.
- $\alpha$ : la vitesse de convergence vers le UFR.
- $N$: le nombre  d’obligations ZC dont le prix est observésur le marché.
- $u_j$: la j-ème  maturité disponible. .
- $\gamma_j$ : les inconnus à ajuster par rapport à la courbe des taux zéro-coupon disponible avant extrapolation.

Pour déterminer ces inconnus, on fixe d’abord $UFR$ et $\alpha$,le vecteur $\gamma$ s’obtient comme solution d’un système d’équations linéaires définies par l’expression du prix de chaque obligation ZC considérée.

Soit :
$$
m_j = P(\mu_j) = e^{-UFR * \mu_j} + \sum_{j=1}^N \gamma_j * W(\tau , \mu_j)
$$

Sous forme matricielle :
$$
m = P = µ + γ ∗ W ⇒ γ = W^{−1}(P − µ)
$$

Avec: 

$m = (m_1, m_2, . . . , m_N)^T$ 

$P = (P(u_1) , P(u_2), . . . , P(u_N))^T$

$µ = (e^{−UFR∗u_1}, e^{−UFR∗u_2}, . . .,e^{-UFR*u_N})^T$

$$
W = 
\begin{bmatrix}
W_{11} \; \; \;. . . &W_{1N} \\
\; \; \; . . . . . ..... \\
W_{N1} \; \; \;. . . &W_{NN}



\end{bmatrix}
$$
$$
W{ij} = W (u_i, u_j) : i = 1 . . . N \;et \;j = 1 . . . N
$$

Aprés la détermination des inconnus, on passe au calcul des prix zéro-coupon correspondants aux maturités pleines, et finalemet deduire les taux zéro-coupon correspondants à ces maturités par la relation suivante :
$$
R(t) = (\frac{1}{P(t)})^{\frac{1}{t}} - 1
$$ 

(**Remarque** : ajouter un grapge si possible )

# VALORISATION DES PROVISIONS TECHNIQUES PRUDENTIELLES:
Les provisions techniques prudentielles sont valorisées brutes de réassurance en considérant les contrats dont l’engagement de l’entreprise est en cours à la date d’inventaire. Les contrats d’assurance non-vie à tacite reconduction dont la date d’effet intervient postérieurement à la date d’inventaire et dont le préavis de résiliation a expiré à cette date sans qu’il y ait une demande de résiliation sont également pris en considération.

Elles sont évaluées comme suit :
$$
PT = BE_{engagement} + BE_{fraisGestion} + MargeRisque
$$

Avec :

- *$PT$* : la provision technique

- *$BE_{engagement}$* : La meilleure estimation des engagements correspond à la somme probabilisée et actualisée de flux de trésorerie futurs afférents aux engagements de l'entreprise d'assurances et de réassurance au titre des contrats souscrits et déterminée, selon la nature des opérations d'assurance

- *$BE_{fraisGestion}$* : La meilleure estimation des frais de gestion correspond à la somme probabilisée et actualisée des flux de frais de gestion des contrats et déterminée, selon la nature des opérations d'assurance.

- *$MargeRisque$* : La marge de risque correspond au coût d'immobilisation du capital de solvabilité requis afférent aux engagements garantis. Elle est calculée, séparément pour les engagements des opérations d'assurances vie et rentes découlant des opérations non vie ainsi que pour les engagements des opérations non vie.

## Opérations d'assurance vie, décès ou capitalisation:
### Meilleure estimations des engagements ($BE_{engagement}$):
Pour les opérations d’assurance vie, décès ou de capitalisation hors unités de compte, la meilleure estimation des engagements comprend la meilleure estimation des garanties probabilisées et les bénéfices discrétionnaires futurs.
$$
_{vie}BE^{engagement} = BE_{garantie}^{prob} + BDF
$$

Avec :

- $BE_{garantie}^{prob}$: la meilleure estimation des garanties probabilisées.
- $BDF$: les bénéfices discrétionnaires futurs.

#### Meilleure estimation des garanties probabilisées: {#sec-MEGP}
La meilleure estimation des garanties probabilisées est calculée garantie par garantie et tête par tête, en actualisant les flux de trésorerie futurs probabilisés, afférents aux engagements garantis à la date d'inventaire. Toutefois, l'entreprise d'assurances et de réassurance peut procéder à une agrégation en retenant des critères homogènes, notamment l'âge et ce, après accord de l'Autorité.
$$
BE_{garantie}^{prob} = \sum\limits_{t=0}^{t=N}\frac{(CF^{Dec}_{t}-CF^{Enc}_{t})}{(1+r_t)^t}
$$
Avec :

- $CF^{Enc}_{t}$: Les encaissements à la date $t$ qui correspondent aux engagements des assurés.
- $CF^{Déc}_{t}$: Les décaissements à la date $t$. qui correspondent aux règlements de toutes prestations garanties au titre des contrats, y compris les rachats. Ils sont déterminés en tenant compte des engagements contractuels et en utilisant, le cas échéant, les bases techniques suivantes :

- **La table de mortalité**: La table de mortalité TV 88-90 pour les assurances en cas de vie ou la table de mortalité TD 88-90 pour les assurances en cas de décès (prévues à l'annexe), auxquelles l'entreprise d'assurances et de réassurance peut substituer une table de mortalité d'expérience, matérialisant la mortalité propre à la population de ses assurés et ce, après accord de l'Autorité ;

- **La table de rachat en montant**.

- **La table de résiliation**.

- **Un taux de sortie en rente**.

**Remarque:**

Les flux de trésorerie futurs probabilisés précités sont déterminés en considérant un horizon de projection suffisant pour la couverture de l’ensemble de la durée de vie des engagements à la date d’inventaire.

**Exemple** :

Si on prend l'exemple d'un contrat d'assurance-vie mixte^[Un contrat d'assurance mixte à prime unique sur $N$ années est un type de contrat d'assurance-vie qui permet de financer l'assurance-vie en une seule fois. Cela signifie que vous payez une prime unique pour couvrir toute la durée du contrat. Ce type de contrat est destiné aux personnes qui disposent d'un capital et souhaitent diversifier leurs placements tout en protégeant leurs proches. Dans sa variante « mixte », elle permet de réaliser un placement rémunérateur tout en assurant une couverture financière à ses proches.] de capital en cas de vie égale au capital en cas de décès $K$.
Soit $q_{x+t}$ la probabilité qu'un individu d'âge $x$ lors de la souscription décéde entre $x+t$ et $x+t+1$. On note $NbPolice_t$ le nombre de police en début de période $t$ et $r_s$ le taux ZC.
La prestation correspondante à ce contrat en date t :
$$
_{décès}CF^{Déc}_{t} = K  \times  NbPolice_t \times q_{x+t} \times (1+r_t)^t
$$

#### Bénéfices discrétionnaires futurs:
Les bénéfices discrétionnaires futurs sont évalués pour chaque ensemble homogène de contrats.

$$
BDF = PPB +\bar{r}^{PB}(SoldeT + SoldeF)\times\mathbf{1}_{(SoldeT + SoldeF) > 0}
$$
Avec :

- **$PPB$** : Le montant de la provision pour participation aux bénéfices, évaluée à la valeur comptable;

- **$SoldeT$** : Somme des soldes techniques.

- **$SoldeF$** : Somme des soldes Financiers.
- **$\bar{r}^{PB}$** : Le taux de participation aux bénéfices moyen servi aux assurés.

**Le taux de participation aux bénéfices moyen servi aux assurés** est calculé en considérant le rapport entre la somme des dotations au titre, des trois derniers exercices clos au moins, affectées à la provision pour participation aux bénéfices afférente aux opérations d'assurance vie, décès ou de capitalisation hors unités de compte et la somme des résultats techniques et financiers des dites opérations sur la même période.

En notation mathématique ça donne :
$$
\bar{r}^{PB} = \frac{Dot_{\geq \text{3 exes clos} }}{RT + RF}
$$

Avec :

- $Dot_{\geq \text{3 exes clos} }$ : somme des dotations au titre, des trois derniers exercices clos au moins.
- $RT$ :les résultats techniques.
- $RF$ :les résultats financiers.

### Meilleure estimation des frais de gestions ($BE_{fraisGestion}$):
La meilleure estimation des frais de gestion correspond à la somme actualisée des flux de frais de gestion futurs probabilisés.
$$
BE_{fraisGestion} = \sum\limits_{t = 1}^{N} \frac{FG_t}{(1+r_t)^t}
$$

Les frais de gestion futurs sont estimés sur la base d’une projection effectuée en considérant un
horizon de projection suffisant pour la couverture de la durée de vie des engagements à la date
d’inventaire. Ils sont déterminés pour chaque année de projection en multipliant le nombre de
contrats par le montant de frais de gestion unitaire moyen.
$$
FG_t = NbContrat_t \times \bar{FG}^{unitaire}_{t}
$$

Avec :

- $\bar{FG}^{unitaire}_{t}$ : Le montant de frais de gestion unitaire moyen est estimé en considérant la moyenne sur les trois derniers exercices clos des montants de frais de gestion unitaires.
- $NbContrat_t$ : Le nombre de contrats précité est estimé par sous-catégories, compte tenu des bases techniques suivantes (La table de mortalité, La table de rachat en nombre, La table de résiliation)
- $FG_t$ : Les frais de gestions.


Le montant de frais de gestion unitaire au titre de chaque exercice clos, correspond au rapport entre le montant de frais de gestion déterminé par sous-catégories et le nombre de contrats ou d'adhérents pour les contrats d'assurance de groupe, à l'ouverture de l'exercice clos considéré.

$$
\bar{FG}^{unitaire}_{t} = \frac{\overbrace{\frac{FG_{t-1}}{NbContrat_{t-1}}}^{\text{Frais de gestion unitaire en t-1}}+\frac{FG_{t-2}}{NbContrat_{t-2}}+\frac{FG_{t-3}}{NbContrat_{t-3}}}{3}
$$


## Rentes découlants des opérations non-vie:
La meilleure estimation des engagements pour les rentes découlant des opérations d’assurance non vie correspond à la meilleure estimation des garanties probabilisées déterminée avant.
$$
BE_{rnv} = BE_{garantie}^{prob}
$$

Avec :

- $BE_{rnv}$ : la meilleure estimation rentes découlant des opérations d'assurance non vie.
- $BE_{garantie}^{prob}$ : la meilleure estimation des garanties probabilisées.

La meilleure estimation des frais de gestion, pour les rentes découlant des opérations d’assurance non vie est déterminée de la meme façon comme avant.

## Opérations d'assurance non vie hors rentes:
### La meilleure estimation des engagements:
la meilleure estimation des engagements comprend la meilleure estimation des engagements pour sinistres nets de recours et la meilleure estimation des engagements pour primes.
$$
_{nvhr}BE_{engagement}= _{nvhr}BE_{sinistres}^{eng} + _{nvhr}BE_{primes}^{eng} 
$$

#### La meilleure estimation des engagements pour primes($_{nvhr}BE_{primes}^{eng}$):
La meilleure estimation des engagements pour primes correspond à la différence entre :

- La somme actualisée des flux de règlements futurs probabilisés nets de recours relatifs aux *sinistres non encore survenus* afférents aux contrats.
- Le montant des primes futures probabilisé et actualisé à la date d'inventaire, net des frais d'acquisition, afférentes aux contrats.

$$
_{nvhr}BE_{primes}^{eng} = \sum_{t \geq 1} \frac{\overline{FRFP_{t}}}{(1+ r_t)^t}- \frac{PFP_t}{(1+ r_t)^t}
$$

avec:

- $PFP$: Le montant des primes futures probabilisé.
- $\overline{FRFP_{t}}$: La somme actualisée des flux de règlements futurs probabilisés nets de recours relatifs aux sinistres non encore survenus,telle que pour une année de projection donnée:

$$
\overline{FRFP_{t}} = Tx_{liquidation} * RS_{moyen} * (PPNA + PFP)
$$

Où:

- $Tx_{liquidation}$: le taux de liquidation,il est estimé en fonction de la cadence de liquidation des engagements pour sinistres survenus.
- $RS_{moyen}$: le ratio de sinistralité moyen telle que: 
$$ 
RS_{moyen_t} = \frac{CU_{t} + CU_{t-1} + CU_{t-2}}{PA_{t} + PA_{t-1}+ PA_{t-2}}
$$

- $CU$: [La charge ultime visée correspond, par exercice de survenance, à la somme des règlements cumulés et des règlements futurs au titre de l'année de survenance considérée.] représente la charge ultime.
- $PA$ les primes acquises.

Tell que :

$$
CU_t = RegCumules_t + RegFutures_t
$$

- $RegCumules_t$ : les règlements cumulés 
- $RegFutures_t$: les règlements futurs
- $PPNA$: La provision pour primes non acquises.
- $PFP$: Le montant des primes futures probabilisé.

#### La meilleure estimation des engagements pour sinistres nets ($_{nvhr}BE_{sinistres}^{eng}$):
La meilleure estimation des engagements pour sinistres nets de recours est déterminée en actualisant, les flux de règlements futurs probabilisés nets de recours relatifs aux sinistres survenus afférents aux contrats.
$$ 
_{nvhr}BE_{sinistres}^{eng} = \sum_{t \geq 1} \frac{FRFP_{t}}{(1+ r_t)^t} 
$$
avec:

- $FRFP_{t}$ : les flux de règlements futurs probabilisés nets de recours relatifs aux *sinistres survenus*, sont estimés sur la base d'un triangle de règlements par année de survenance net de recours conformément à la méthode  l'annexe N°5.

### La meilleure estimation des frais de gestion:
la meilleure estimation des frais de gestion correspond à la somme actualisée des flux de frais de gestion futurs liés aux contrats.
$$
_{nvhr}BE_{fraisGestion}= \sum_{t \geq 1} \frac{FFGF_t}{(1+r_t)^t}
$$

avec: 

- $FFGF$: les flux de frais de gestion futurs. telle que:
$$
FFGF = Tx_{fraisGestion_{moy}} * (_{nvhr}BE_{sinistres}^{eng} + _{nvhr}BE_{primes}^{eng})
$$

et:

- $Tx_{frais gestion_{moy}}$ : Le taux de frais de gestion moyen,il est estimé, par sous-catégories d’opérations d’assurance, en considérant la moyenne sur les trois derniers exercices clos des taux de frais de gestion.

Donc:

$$
_{t}Tx_{fraisGestion_{moy}}= \frac{Tx_{fraisGestion_{t}} + Tx_{fraisGestion_{t-1}} + Tx_{fraisGestion_{t-2}}}{3}
$$

ainsi que :

$$
Tx_{frais gestion_{t}} = \frac{FG}{_{nvhr}BE_{sinistres}^{eng}+ Reglements_{Clos}}
$$

- $FG$: le montant frais de gestion.
- $Reglements_{Clos}$ : les règlements au titre de l’exercice clos.


## Part des cessionnaires dans les provisions techniques prudentielles:
La part des cessionnaires dans les provisions techniques prudentielles est évaluée en considérant la différence entre d'une part, la meilleure estimation des engagements cédés et d'autre part, l'ajustement pour défaut de contrepartie.

$$
Part_{cess} = BE_{cedes}^{eng} - Ajust_{DC}
$$

### La meilleure estimation des engagements cédés ($BE_{cedes}^{eng}$):
#### Les opérations d'assurance vie, décès ou de capitalisation {-}
la meilleure estimation des engagements cédés est évaluée en multipliant la meilleure estimation des
engagements par le rapport entre d’une part, la part des cessionnaires dans les provisions
mathématiques et dans les provisions pour capitaux, rentes et rachats à payer et d’autre part, la
somme des provisions mathématiques , des provisions pour capitaux, rentes et rachats à payer bruts
de réassurance.

$$
_{vie}BE_{cedes}^{eng} = taux_c \times _{vie}BE^{eng}
$$
Avec :

- $taux_c$ (taux de cession): le rapport entre d'une part, la part des cessionnaires dans les provisions mathématiques et dans les provisions pour capitaux, rentes et rachats à payer et d'autre part, la somme des provisions mathématiques, des provisions pour capitaux, rentes et rachats à payer bruts de réassurance.


#### Les opérations non vie{-}
Pour les opérations non vie, la meilleure estimation des engagements cédés correspond à la somme de la meilleure estimation des engagements pour sinistres cédés et de la meilleure estimation des engagements pour primes cédés.
$$
_{nvie}BE_{cedes}^{eng} =\; _{sinsitres}BE_{cedes}^{eng} + \; _{primes}BE_{cedes}^{eng}
$$
Avec :

> $_{sinsitres}BE_{cedes}^{eng} = taux_s \times BE_{sinsitres}^{eng}$ : La meilleure estimation des engagements pour sinistres cédés visée à la spécification technique 33 ci- dessus est évaluée en multipliant la meilleure estimation des engagements pour sinistres nets de recours visée à par ($taux_s$) le rapport entre la part des cessionnaires dans les provisions pour sinistres à payer et la provision pour sinistres à payer brute de réassurance.

> $_{primes}BE_{cedes}^{eng} = r^{primes}_{cession} \times BE_{primes}^{eng}$ : La meilleure estimation des engagements pour primes cédés visée est évaluée en multipliant la meilleure estimation des engagements pour primes visée par le taux de cession de primes. Le taux de cession ($r^{primes}_{cession}$) de primes précité correspond au rapport entre les primes brutes non vie (cessions) et les primes émises de l'exercice.

### L'ajustement pour défaut de contrepartie:

L'ajustement pour défaut de contrepartie est déterminé en actualisant les flux d'ajustement futurs sur la base de la courbe des taux fixée par l'Autorité.

Les flux d'ajustement futurs sont déterminés conformément à la méthode, telle que décrite à **l'annexe N°6** de la circulaire de l'ACAPS.

# Capital de Solvabilité Requis :
Le Capital de Solvabilité Requis (CSR) est une notion très importante dans les domaines d’assurance et de réassurance, il permet la garantie de tous les risques quantifiables auxquels les entreprises de ces domaines sont exposés.  Le CSR correspond au capital dont a besoin une entreprise d'assurance ou de réassurance pour faire face à tous les risques qui peuvent survenir dans le futur et limiter la probabilité de ruine à 0,5%, c'est-à-dire à une seule occurrence tous les 200 ans.   

Commençons d’abord par la définition des différents risques dans les secteurs d’assurance et de réassurance :

- **Risque de souscription** : le risque de perte ou de changement défavorable de la situation financière, en
raison d'hypothèses inadéquates en matière de sinistralité, de tarification et de provisionnement.  

- **Risque de marché** : le risque de perte ou de changement défavorable de la situation financière
résultant, directement ou indirectement, de fluctuations affectant le niveau de la valeur des actifs, des
passifs et des instruments financiers.

- **Risque de spread** (marge de crédit) : le risque de perte ou de changement défavorable de la situation
financière résultant des changements touchant les marges additionnelles par rapport aux taux de
référence exigée par les investisseurs sur les emprunts émis par des entités autres que l’Etat.

- **Risque de contrepartie** : le risque de perte ou de changement défavorable de la situation financière
résultant d’un défaut de paiement d’une contrepartie ou d’une dégradation de sa qualité de crédit.

- **Risque opérationnel** : le risque de perte ou de changement défavorable de la situation financière
résultant de procédures internes, de membres du personnel, de systèmes inadéquats ou défaillants,
ou d'événements extérieurs.

- **Risque de concentration** : le risque de perte ou de changement défavorable de la situation financière
résultant d’un manque de diversité des émetteurs auxquels l’entreprise d’assurances et de
réassurance est exposée.

Selon le circulaire de l’ACAPS (l’Autorité de Contrôle des Assurances et de la Prévoyance Sociale) publié le premier Janvier 2020, Le capital de solvabilité requis est constitué de la somme des éléments suivants :

- Le capital de solvabilité requis de base.  

- L’exigence de capital relative au risque opérationnel.

- L’ajustement visant à tenir compte de la capacité d’absorption des pertes par les assurés.

- L’ajustement visant à tenir compte de la capacité d’absorption des pertes par les impôts différés.

## Le capital de solvabilité requis de base $CSR_{base}$
Le capital de solvabilité requis de base est le montant total des exigences de capitaux liées aux risques de *marché*, de *concentration*, de *contrepartie*, de *souscription* vie et de *souscription non-vie* et ce, après application des coefficients de corrélations.
$$
CSR_{base} = \sqrt{\sum_{i,j\in Risk }(\rho_{i,j} * CSR_{i} * CSR_{j})}
$$
avec : 

- Risk $\in$ \{Marché, Concentration, Contrepartie, Souscription Vie, Souscription Non - Vie\} 

- $\rho$ : Coefficients de corrélations.

avec la matrice de corrélations suivante:

|               |Marché |Concentration|Contrepartie|Sousc. vie|Sousc. non-vie|
|---------------|-------|-------------|------------|----------|--------------|
|Marché         |   1   |  x          |    x       |      x   |  x           |
|Concentration  | x     |     1       |   x        |    x     |  x           |
|Contrepartie   |  x    |    x        |  1         |    x     | x            |
|Sousc. vie     |  x    |    x        |   x        |   1      | x            |
|Sousc. non-vie | x     |    x        |   x        |   x      |  1           |

### EXIGENCE DE CAPITAL RELATIVE AUX RISQUES DE MARCHE $CSR_{marche}$
L’exigence de capital relative au risque de marché est le montant total des exigences de capitaux relatives aux sous-risques action, taux, immobilier, écart de taux et change et ce, après application des coefficients de corrélations.
$$
CSR_{marche} = \sqrt{\sum_{i,j\in RM }(\rho_{i,j} * CSR_{i} * CSR_{j})} 
$$
avec : 

- RM $\in$ \{action, taux, immobilier, écart de taux et change\} 

- $\rho$ : Coefficients de corrélations.

#### L’exigence de capital relative au risque action ($CSR_{action}$)
L’exigence de capital relative au risque action est le montant de la perte de fonds propres résultant des baisses simultanées des valeurs des actions.

Les taux de baisse à appliquer pour le calcul de l’exigence précitée sont fixés pour les catégories d’actions suivantes:

• Actions cotées à long terme

• Autres actions cotées

• Actions non cotées à long terme

• Autres actions non cotées

• Entités d’infrastructures

$$
CSR_{action} = VM_{action}^{\text{cas de baisse}} - VM_{action} 
$$

#### L’exigence de capital relative au risque de taux ($CSR_{taux}$)
L’exigence de capital relative au risque de taux, est le montant de la perte maximale de fonds propres qui résulterait de l’application de coefficients à la baisse ou à la hausse à la courbe des taux sur tout actif ou passif.

$$
CSR_{taux} = max (CSR_{taux-hausse}; CSR_{taux-baisse})
$$
avec : &nbsp; $CSR_{taux-i} = BE^{scénario-i} - BE$     <span style="display:inline-block;width:2cm;"></span>  $i \in \{ hausse,baisse \}$

#### L’exigence de capital relative au risque immobilier ($CSR_{immobilier}$)
L’exigence de capital relative au risque immobilier est la perte de fonds propres due à une baisse de X% de la valeur des actifs immobiliers.
$$
CSR_{immobilier} = BE_{eng}^{\text{baisse actifs immobiliers}} - BE_{eng}
$$

#### L’exigence de capital relative au risque d’écart ($CSR_{\text{Ecart_taux}}$)
L’exigence de capital relative au risque d’écart de taux est la perte de fonds propres due à l’application des taux de baisse à la valeur des titres de créances non émis ou non garantis par l’Etat.

Les taux de baisse à appliquer sont calculés en fonction de la duration et de la prime de risque à l’émission.

#### L’exigence de capital relative au sous-risque de change ($CSR_{change}$)
L’exigence de capital relative au sous-risque de change correspond à la somme des exigences de capitaux pour risque de change pour chaque devise étrangère.

L'exigence de capital pour risque de change pour chaque devise étrangère correspond à la plus élevée des exigences de capitaux suivantes:

- l'exigence de capital pour risque d'augmentation de la valeur de la devise étrangère par rapport au dirham.
- l'exigence de capital pour risque de diminution de la valeur de la devise étrangère par rapport au dirham.

L'exigence de capital pour risques d'augmentation ou de diminution de la valeur de la devise étrangère par rapport au dirham est egale  à la perte de fonds propres qui résulterait des scénarios d’augmentation ou de diminution, respectivement de $X\%$ et $X\%$, de la valeur de la devise étrangère par rapport au dirham.

$$
CSR_{change} = \sum_{i\in RC} CSR^{change}_{i}
$$
avec : $RC$ = \{risque de change pour chaque devise étrangère \}
 et 
$$
CSR^{change}_{i} = max (CSR^{augmentation}_{i} ; CSR^{diminution}_{i})
$$
- augmentation : le risque d'augmentation de la valeur de la devise étrangère par rapport au dirham.
- diminution : le risque de diminution de la valeur de la devise étrangère par rapport au dirham.

tel que: &nbsp; $CSR^{j}_{i} = BE^{\text{scénario j}} - BE$ <span style="display:inline-block;width:2cm;"></span> $j \in \{ augmentation ; diminution\}$ 
  
### Exigence de capital relative au risque de contrepartie ($CSR_{contrepartie}$)
L’exigence de capital relative au risque de contrepartie est le montant total des exigences de capitaux relatives aux sous-risques de contrepartie de *type 1* et de *type 2*   , une fois les coefficients de corrélation appliqués.
$$
CSR_{contrepartie} = \sqrt{\sum_{i,j\in type}(\rho_{i,j}\times CSR_{contrepartie}^{i}\times CSR_{contrepartie}^{j})}
$$
avec : $type \in \{type 1 ; type 2\}$

#### Exigence de capital relative au risque de contrepartie de type 1:
L’exigence de capital relative au risque de contrepartie de type 1 est calculé en fonction des montants
de pertes en cas de défaut des cessionnaires, des cédantes et des organismes dépositaires, selon la
méthode suivante: ** voir l'annexe 9**

**1ère étape:** Calcul des pertes en cas de défaut des différentes contreparties $i$.

- Pour un contrat de réassurance:

$$
LGD_{i} = max (X * (BE_{cédée_{i}} + \text{créances sur les cessionaires} + AR_i) - \text{Dépot en espèces ou en valeur};0)
$$
Où :

- $BE_{cédée_{i}}$ : La meilleure estimation des engagements cédés au cessionnaire ;
- $LGD_{i}$ : la perte en cas de défaut du cessionnaire i ;
- $\text{Depot en espèces ou en valeur}$ : le montant des dépôts en espèces ou en valeurs du cessionnaire i ;
- $AR_i$ : le montant d’atténuation du risque via les différents contrats de réassurance conclus avec le cessionnaire i. Il correspond à la différence entre les montants d’exigences de capital pour les risques de souscription vie et non-vie calculés compte non tenu de la réassurance et compte tenu de la réassurance.

- Pour un contrat d’acceptation:
$$
LGD_{i} = max (\text{Dépôts en espèces aupret de la cédante }_i + \text{Créance sur la cédante}_i - \text{Provision techniques}_i;0  )
$$
Où :

- $LGD_{i}$: la perte en cas de défaut de la cédante i ;
- $\text{Dépôts en espèces aupret de la cédante }_i$ : le montant des dépôts en espèces déposés chez la cédante i ;
- $\text{Provision techniques}_i$ : le montant des provisions techniques acceptées avec la cédante i

- Pour un avoir auprès d’un organisme dépositaire :
$$
LGD_{i} = max (\text{Avoirs en banque}_i;0)
$$
Où :

-$LGD_{i}$ : la perte en cas de défaut de la banque i ;

**2ème étape:** Sommation des LGD par échelle de notation :

Pour chaque échelle de notation $k$ :
$$
TLGD_{K} = \sum_{\text{Contrepartie faisant partie de la même échels de notation k}} LGD_k
$$

**3ème étape:** Calcul des volumes suivants :
$$
V_{inter} = \sum_{j,k} \frac{PD_k * (1-PD_k) * PD_j * (1-PD_j)}{X * (PD_j+PD_k)-PD_j*PD_k} * TLGD_j *TLGD_k
$$
$$
V_{inter} = \sum_{j} \frac{X* PD_j * (1-PD_j)}{X - PD_j} * \sum_{PD_j} LGD_{i}^{2}
$$
Où :

- $PD_j$ et$PD_k$: probabilités de défaut des contreparties j et k, établies conformément au tableau prévu au 2) de l’annexe n°12.
- $TLGD_j$ et $TLGD_k$ : somme des pertes en cas de défaut pour les contreparties dont la probabilité de défaut est, respectivement, de $PD_j$ et$PD_k$.
- $\sum_{PD_j} LGD_{i}^{2}$ : somme couvrant toutes les expositions dont la probabilité de défaut est de $PD_j$.

**4ème étape:** Calcul du de la façon suivante :
$$
CSR_{contrepartie}^{type1} = \begin{cases}
X * \sqrt{V_{inter} + V_{intra}}; \; & \text{si} \; \frac{\sqrt{V_{inter} + V_{intra}}}{\sum_i LGD_{i}} \leq x1 \\
X * \sqrt{V_{inter} + V_{intra}}; \; & \text{si} \; x1 \leq\frac{\sqrt{V_{inter} + V_{intra}}}{\sum_i LGD_{i}} \leq x2 \\
\sum_i LGD_{i}  & \text{si} \; \frac{\sqrt{V_{inter} + V_{intra}}}{\sum_i LGD_{i}} \geq x2 \\
\end{cases}
$$

#### Exigence de capital relative au risque de contrepartie de type 2:
L’exigence de capital relative au risque de contrepartie de type 2 est le montant total des
exigences de capitaux relatives aux risque de contrepartie des assurés, des intermédiaires et des
autres contreparties :
$$
CSR_{contrepartie}^{type2} = CSR_{contrepartie}^{Assures} + CSR_{contrepartie}^{Intermediaires} + CSR_{contrepartie}^{autres-contreparties}
$$
avec :

1) L’exigence de capital relative au risque de contrepartie des assurés correspond à $X\%$ des créances relatives aux primes ou cotisations qui demeurent impayées six (06) mois après la date de leur émission. Les créances précitées s’entendent nettes de provisions.

2) L’exigence de capital relative au risque de contrepartie des intermédiaires correspond à $X\%$ des créances sur les intermédiaires d’assurances nettes de provisions.

3) L’exigence de capital relative au risque lié aux autres contreparties correspond à $X\%$ de la somme des créances de l’actif circulant, autres que les créances vis-à-vis de l’Etat des contreparties visées aux 1) et 2) ci-dessus et les montants des chèques et valeurs à encaisser, nettes de provisions et qui demeurent impayées pendant une période supérieure à six (06) mois.

### Exigence de capital relative au risque de concentration ($CSR_{concentration}$)
L’exigence de capital relative au risque de concentration correspond à la perte des fonds propres due à la baisse des actifs associés aux ensembles d’émetteurs appartenant aux mêmes groupes. Elle correspond à la racine carrée de la somme des carrés des exigences de capitaux relatives au sous-risque de concentration relatifs aux différents groupes d’émetteurs.
$$
CSR_{concentration} = \sqrt{\sum_i CSR_i^2}
$$
avec $i \in \{ \text{Les sous-risques de concentration relatifs aux differents groupes d’emetteurs.}\}$ 

Pour chaque groupe d’émetteurs, l’exigence de capital relative au risque de concentration egale à $X\%$ de l’écart positif constaté entre le montant des placements de l’entreprise d’assurances et de réassurance, autres que les valeurs de l’Etat ou celles jouissant de sa garantie, relatifs à l’ensemble d’émetteurs appartenant au groupe précité et $X\%$ du total de ses placements.

### Exigence de capital relative au risque de souscription vie ($_{souscription}CSR_{vie}$)
L’exigence de capital relative au risque de souscription vie est la somme total des exigences de capitaux relatives aux sous-risques de mortalité, de longévité, de rachat, de frais et de catastrophe, on appliquant les coefficients de corrélations entre ces sous-risques.
$$
_{souscription}CSR_{vie} = \sqrt{\sum_{i,j} ( \rho_{i,j}\times CSR_i \times CSR_j)}
$$
avec : $i,j \in \{\text{mortalite, longevite, rachat, frais  catastrophe} \}$

#### Exigence de capital pour risque de mortalité ($CSR_{mortalite}$)
L’exigence de capital pour risque de mortalité correspond à la perte de fonds propres due à la hausse de $X\%$ des taux de mortalité retenus pour le calcul des provisions techniques prudentielles.

La hausse des taux de mortalité précitée ne s'applique qu'aux contrats d'assurance pour lesquels une
hausse des taux de mortalité entraîne une augmentation des provisions techniques prudentielles.

$$
CSR_{mortalite} = BE^{hausse} - BE
$$

#### Exigence de capital pour risque de longévité ($CSR_{longévité}$)
L’exigence de capital pour risque de longévité correspond à la perte de fonds propres qui résulterait de la baisse de $X\%$ des taux de mortalité retenus pour le calcul des provisions techniques prudentielles.

La baisse des taux de mortalité précitée ne s'applique qu'aux contrats d'assurance pour lesquels une
baisse des taux de mortalité entraîne une augmentation des provisions techniques prudentielles.
$$
CSR_{longévité} = BE^{baisse} - BE
$$

#### Exigence de capital pour risque de rachat ($CSR_{rachat}$)
L’exigence de capital pour risque de rachat est correspond au maximun entre les exigences de capitaux suivantes:

- L’exigence de capital pour risque de hausse des taux de rachat : cette exigence signifie la perte de fonds propre qui résulterait d’une revalorisation des provisions techniques prudentielles suite à une hausse de $X\%$ des taux de rachat retenus, en montant et en nombre. Toutefois, les taux de rachat augmentés de la hausse précitée ne doivent pas dépasser $X\%$.

La hausse des taux de rachat précitée ne s'applique qu'aux contrats d'assurance pour lesquels une hausse des taux de rachat entraîne une augmentation des provisions techniques prudentielles.

- L’exigence de capital pour risque de baisse des taux de rachat : cette exigence correspond à la perte de fonds propre qui résulterait d’une revalorisation des provisions technique prudentielles due à une baisse de X\% des taux de rachat retenus, en montant et en nombre.

La baisse des taux de rachat précitée ne s'applique qu'aux contrats d'assurance pour lesquels une baisse des taux de rachat entraîne une augmentation des provisions techniques prudentielles.

$$
CSR_{rachat} = max(CSR_{rachat}^{\text{hausse taux}}; CSR_{rachat}^{\text{baisse taux}})
$$
avec : 
$$
CSR_{rachat}^{\text{hausse taux}} = BE_{rachat}^{\text{hausse taux}} - BE
$$
$$
CSR_{rachat}^{\text{baisse taux}} = BE_{rachat}^{\text{baisse taux}} - BE
$$

#### Exigence de capital relative au risque de frais ($CSR_{frais}$)
L’exigence de capital relative au risque de frais correspond à la perte de fonds propres due à des augmentations combinées de :

- $X%$ du montant de frais de gestion unitaire moyen retenu pour le calcul des provisions techniques prudentielles des opérations d’assurance vie, décès ou de capitalisation et des rentes découlant des opérations non-vie et ce, par sous-catégorie;
- $X%$ par année de projection du montant de frais de gestion unitaire moyen précité.
$$
CSR_{frais} = BE_{frais}^{\text{chocé}} - BE_{frais}
$$

#### Exigence de capital relative au risque de catastrophe ($CSR_{catastrophe}$)

L’exigence de capital relative au risque de catastrophe vie correspond à l’application d’un coefficient de $X\%$ aux montants des capitaux sous risque relatifs aux garanties en cas de décès nets de réassurance.

### Exigence de capital relative au risque de souscription non vie ($_{souscription}CSR_{non-vie}$)
L’exigence de capital relative au risque de souscription non-vie est la somme totale des exigences de capitaux relatives aux \textbf{sous-risques de primes, de provisions et de catastrophe non-vie}, une fois les coefficients de corrélation appliqués..

$$
_{souscription}CSR_{non-vie} = \sqrt{\sum_{i,j} ( \rho_{i,j} \times CSR_i \times CSR_j)}
$$

avec : $i,j \in \{ \text{primes, provisions, catastrophe} \}$
et $\rho$ es le coefficient de corrélation.

#### Exigence de capital relative au sous-risque de primes ($CSR_{primes}$)
L’exigence de capital relative au sous-risque de primes est le montant total  des exigences de capitaux relatives aux sous-risques de primes par sous-catégorie et ce, après application des coefficients de corrélations.
$$
CSR_{primes} = \sqrt{\sum_{i,j} ( \rho_{i,j}* CSR_i * CSR_j)}
$$
avec : $i,j \in \{ \text{Les sous-risques de primes par sous-categorie }\}$
et $\rho$ es le coefficient de corrélation entre les sous-catégories des sous-risques de primes.

Pour chaque sous-catégorie, l’exigence de capital afférente au sous risque de primes est égale à X fois le produit de l’écart-type de primes et du montant des primes acquises augmenté de la provision pour primes non-acquises nettes de réassurance au titre de l’exercice inventorié.
$$
CSR_{sous-categorie}^{primes} = X * \sigma_{primes} * BE_{primes}
$$

avec : &nbsp; $BE_{primes} = Primes_{acquises}^{nettes} + Provision_{primes_{non-acquise}}^{nettes}$

#### Exigence de capital relative au sous-risque de provisions ($CSR_{provisions}$)
L’exigence de capital relative au sous-risque de provisions est la somme total des exigences de capitaux relatives aux sous-risques de provision par sous-catégorie, on prenant on considration les coefficients de correlation entre les sous-risques.
$$
CSR_{provisions} = \sqrt{\sum_{i,j} ( \rho_{i,j}* CSR_i * CSR_j)}
$$
avec : $i,j \in \{ Les sous-risques de provisions par sous-categorie \}$
et $\rho$ es le coefficient de corrélation entre les sous-catégories des sous-risques de provisions.

Pour chaque sous-catégorie, l’exigence de capital afférente au sous risque de provision est égale à X fois le produit de l’écart-type de provisions et du montant de la meilleure estimation des engagements pour sinistres nette de réassurance.
$$
CSR_{sous-categorie}^{provisions} = X * \sigma_{provisions} * BE_{engagements}
$$

#### Exigence de capital relative au risque de catastrophe non-vie
L’exigence de capital relative au risque de catastrophe non-vie correspond au racine carrée de la somme des carrés des exigences de capitaux relatives au sous-risque de catastrophe non-vie des garanties suivantes :

- Individuelles accidents et Invalidité ;
- Maladie;
- Accidents du travail et maladies professionnelles ;
- Responsabilité civile automobile des véhicules terrestres à moteur;
- Responsabilité civile (autre que la responsabilité civile automobile et la responsabilité civile résultant de l'emploi de véhicules fluviaux ou maritimes ou de l'emploi des aéronefs) ;
- Incendie ;
- Maritime corps, facultés et responsabilité civile résultant de l'emploi de véhicules fluviaux et maritimes ;
- Aviation corps et responsabilité civile résultant de l'emploi des aéronefs ;
- Marchandises transportées par voie terrestre ;
- Assurance récolte, grêle ou gelée et éléments naturels ;
- Crédit et caution

## Exigence de capital relative au risque opérationnel ($CSR_{opérationnel}$)

L’exigence de capital relative au risque opérationnel correspond à X\% du capital de solvabilité requis de base.
$$
CSR_{opérationnel} = X\% * CSR_{base}
$$

## Ajustement du capital de solvabilité requis

### Ajustement visant à tenir compte de la capacité d’absorption des pertes par les assurés ($Adj_{assures}^{Pertes}$)

L’ajustement visant à tenir compte de la capacité d’absorption des pertes par les assurés egale au minimum de l’écart entre le capital de solvabilité requis de base calculées brutes et nettes d’absorption par les assurés, d’une part, et le montant des bénéfices discrétionnaires futures d’autre part.
$$
Adj_{assures}^{Pertes} = min (CSR_{base}^{nettes}-CSR_{base}^{brutes};BDF)
$$

### Ajustement visant à tenir compte de la capacité d’absorption des pertes par les impôts différés ($Ajt_{\text{impots differes}}^{Pertes}$)

L’ajustement visant à tenir compte de la capacité d’absorption des pertes par les impôts différés correspond au produit du taux d’impôts et le minimum de la somme du capital de solvabilité requis de base et l’exigence de capital relative au risque opérationnel diminuée de l’ajustement visant à tenir compte de la capacité d’absorption des pertes par les assurés, d’une part, et l’écart positif entre les impôts différés-passif et les impôts différés-actif, d’autre part.
$$
Ajt_{\text{impots differes}}^{Pertes} = Tx_{impots} \times min(CSR_{base} + CSR{operationnel} - Adj_{assures}^{Pertes} ; Impots_{passif}^{differes} - Impots_{actif}^{differes})
$$

:::{.callout-tip}
**Remarque**

Dans le cas où l’écart entre les impôts différés-passif et les impôts différés-actif est négatif, l’ajustement précité est nul.
:::





















